### ISSUE TITLE
Error in RestSerializable when hydrating after deletion

### ISSUE THREAD

**Issue by polRk** [greenbits/brick#104]
TaskDto
```dart
@ConnectOfflineFirstWithRest(
  restConfig: RestSerializable(
    fieldRename: FieldRename.none,
    fromKey: 'items',
    endpoint: r'''{
      if (query.action == QueryAction.get && query?.where != null) {
        final byId = Where.firstByField('id', query.where);

        if (byId?.value != null) {
          return "/tasks/${byId.value}";
        }
      }

      if (query?.action == QueryAction.delete) {
        return "/tasks/${instance.id}";
      }

      return "/tasks";
    }''',
  ),
)
```

flutter: FINEST: 2020-12-10 11:37:36.095433: #delete: url= statusCode=200 body=
flutter: FINEST: 2020-12-10 11:37:36.096858: #hydrate: TaskDto {"action":4,"providerArgs":{}}
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'id' was called on null.
Receiver: null
Tried calling: id

Error in this line

```dart
      if (query?.action == QueryAction.delete) {
        return "/tasks/${instance.id}";
      }
```

**Comment by tshedor** [comment]
Hey @polRk, that means that you're passing in a `null` instance when you invoke `delete<TaskDto>(.....your instance....)`. You should either make sure the instance is not null or `return null` when instance is null. For example:

```dart
if (query?.action == QueryAction.delete && instance == null) {
  return null
}
```

However, again, I would encourage you to treat the Adapter as your Data Transfer Object. The generated code translates to and from multiple sources, which is the purpose of a DTO. That way, you're passing through an instance of `Task` instead of a DTO.

**Comment by polRk** [comment]
@tshedor Thank you! Delete request is ok, but error in hydrate block.

In my code, I can't find where I pass a null.

```dart
  @override
  Future<Either<ErrorException, bool>> deleteTask(TaskDto task) {
    return handleException(delete<TaskDto>(task));
  }
```

```dart
  @action
  Future<void> deleteRootTask(TaskEntity task) async {
    (await _repository.deleteTask(taskCodec.encode(task))).fold(
      (l) => handleError(l),
      (r) => tasks.remove(task.id),
    );
  }
```

```dart
  @override
  TaskDto convert(TaskEntity taskEntity) {
    return TaskDto(
      id: taskEntity.id,
      createdAt: _toUTC(taskEntity.createDateTime),
      updatedAt: _toUTC(taskEntity.updateDateTime),
    )..primaryKey = taskEntity.primaryKey;
  }
```

**Comment by tshedor** [comment]
@polRk The code you originally posted looks like it's from the `endpoint` configuration. Is that correct? What is the hydrate block error?

The code snippets you've provided aren't filtering out null objects. Are you certain that one of these entities is not `null`?

**Comment by polRk** [comment]
@tshedor  

> Are you certain that one of these entities is not null?

Yes, i'm sure.

> What is the hydrate block error?

Brick has autoHydrate logic. After delete request is followed by hydrate

**Comment by tshedor** [comment]
@polRk based on the code you've submitted, an entity is in fact null somewhere, otherwise it wouldn't be throwing the error. Have you set up debugging for all exceptions? Are you able to narrow the break using the stack trace reported by a Flutter IDE plugin, like the one in VS Code? Or are you able to see the full exception stack in the terminal when using `flutter run`?

**Comment by tshedor** [comment]
@polRk based on the code you've submitted, an entity is in fact null somewhere, otherwise it wouldn't be throwing the error. Have you set up debugging for all exceptions? Are you able to narrow the break using the stack trace reported by a Flutter IDE plugin, like the one in VS Code? Or are you able to see the full exception stack in the terminal when using `flutter run`?

**Comment by polRk** [comment]
@tshedor 
```
flutter: │ 🐛 #hydrate: RecurrenceExceptionDto {"action":0,"providerArgs":{"limit":1},"where":[{"subclass":"Where","evaluatedField":"primaryKey","compare":0,"required":true,"value":3}]}
flutter: └───────────────────────────────────────────────────────────────────────────────
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ \^[[0m\^[[39m\^[[48;5;196mNoSuchMethodError: The getter 'value' was called on null.<…>
flutter: \^[[38;5;196m│ \^[[0m\^[[39m\^[[48;5;196mReceiver: null<…>
flutter: \^[[38;5;196m│ \^[[0m\^[[39m\^[[48;5;196mTried calling: value<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   Object.noSuchMethod (dart:core-patch/object_patch.dart:51:<…>
```

**Comment by tshedor** [comment]
@polRk it would appear that you're querying an association improperly from the API.

This is throwing on the association method, which means that at some point your `restEndpoint` is expecting an instance to use but is not receiving one. This could mean that a query to a member endpoint (e.g. `tasks/${instance.id}`) failed or that your default endpoint is returning an expected, unparseable response by the adapter.

Further, this error is not caused by Brick but is instead coming from the implementation of `restEndpoint` as described by the stack track. `restEndpoint` is forwarded from the `ConnectOfflineFirstWithRestAnnotation` directly into the adapter. Unless you've subclassed your `getAssociation` to invoke `delete`, the code you've provided doesn't map to the error. This is strictly a get request.

Again, I strongly, **strongly**, strongly encourage you to abandon using Data Transfer Objects and trust Brick to generate DTOs for you as adapters. I worry it's making debugging more difficult than it needs to be.

**Comment by polRk** [comment]
Just why do hydrate after successfully removing the recurrence rule

<img width="1639" alt="Screenshot 2020-12-24 at 13 14 04" src="https://user-images.githubusercontent.com/39828645/103081855-e7961000-45e9-11eb-85db-d98f7a278577.png">

**Comment by polRk** [comment]
What does brick expect after successful deletion ?

**Comment by polRk** [comment]
This bug is related to the search request in the offline queue table #111
