### ISSUE TITLE
Problem with headersForQuery

### ISSUE THREAD

**Issue by pkozlovskiy** [greenbits/brick#111]
Hi!
I use my http client for RestProvider where i get actual token and add Authorization header BUT in this way offlineRequestQueue was broken, because in OfflineQueueHttpClient we cache request (without auth header) and only after call 
 _inner.send
wich add new Authorization header, and there fore RequestSqliteCache cant`t delete success response because headers not the same(
I try use defaultHeaders, but token can be changed.

I think ovveride of headersForQuery is the best way for this problem ( but it protected)

**Comment by polRk** [comment]
It's little fix.

- Save old headers;
- Add new headers;
- Send request
- Wait response
- Remove new headers
- Return response

```dart
  Future<http.StreamedResponse> send(http.BaseRequest request) async {
    final token = await _tokenRepository.getIdToken();
    final oldHeaders = request.headers;
     
    request.headers['Authorization'] = 'Bearer $token';
    request.headers['Content-Type'] = 'application/json; charset=utf-8';
    
    final response = await _inner.send(request);
    
    request.headers.clear();
    request.headers.addAll(oldHeaders);
    
    return response;
  }
```

**Comment by polRk** [comment]
Brick use this headers ```{"content-type":"text/plain; charset=utf-8"}```, but we removed all headers in the request.

**Comment by polRk** [comment]
<img width="558" alt="Screenshot 2020-12-26 at 17 16 11" src="https://user-images.githubusercontent.com/39828645/103153012-47cdb300-479e-11eb-963f-837793a4c5bd.png">

**Comment by polRk** [comment]
But if you want to use providerArgs with custom httpClient, you should add

```
final defaultHeaders = <String, String>{
  'Content-Type': 'application/json; charset=utf-8'
};

final providerArgs = <String, dynamic>{
  'request': 'PUT',
  ...defaultHeaders,
};

...

restProvider: RestProvider(client: client)..defaultHeaders = defaultHeaders,
```

**Comment by tshedor** [comment]
Thanks @polRk for helping out with this one!

@pkozlovskiy Are you subclassing `RequestSqliteCache`? It sounds like you might be if you're mutating the headers on subsequent retries.

In this use case, I would instead recommend `implements` over `extends` so that you're not storing the headers or making SQLite queries based on the headers. 

I hadn't anticipated this sort of usage, so my other suggestion is to open a PR and make `_findRequestInDatabase` a [`@visibleForOverriding`](https://api.flutter.dev/flutter/meta/visibleForOverriding-constant.html) method. That way, you'll be able to ignore the headers column (since these change) in subsequent lookups and you'll be able to `extends RequestSqliteCache` without rewriting a lot of the functionality. I also think making `headersForQuery` a method that's `@visibleForOverriding` instead of `@protected` would be useful.

**Comment by tshedor** [comment]
@pkozlovskiy With #122 merged I'm going to close, please reopen if you're still having trouble
