### ISSUE TITLE
Associations are not being sent to rest endpoint

### ISSUE THREAD

**Issue by mrmeyers99** [greenbits/brick#115]
I'm confused how adding children of a parent object is supposed to work.  In the example project I added the following code to the top of the `build` method in `_MyHomePageState`.

```
    if (migrated) {
      Repository().get<Customer>().then((customers) {
        customers[0].pizzas.add(Pizza(id: 5, toppings: [Topping.pepperoni], frozen: false));
        Repository().upsert(customers[0]);
      });
    }
 ```
 
 The app does not ever post to `/pizzas`.  If I upsert the pizza first, then it does, but brick isn't sending any information to the rest server that tells it which customer the pizza is associated to.  Am I doing something wrong?

**Comment by tshedor** [comment]
@mrmeyers99 The app doesn't post to `/pizzas` because you're upserting a customer. You should revise your upsert to include the type - `upsert<Customer>(customers[0])`. It will only notify the `/customers` endpoint, or whatever is defined in `endpoint:`. 

However, depending on how the association is defined, pizza data will be transmitted. 

Since the association is [defined with an `OfflineFirstWhere` association](https://github.com/greenbits/brick/blob/master/example/lib/app/models/customer.dart#L35-L37), the payload will be the inverse of the ids: 

```dart
@OfflineFirst(where: {'id': "data['pizza_ids']"})
@Rest(name: 'pizza_ids')
final List<Pizza> pizzas;
```

And [in the adapter](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/example/lib/app/adapters/kitchen_sink_adapter.g.dart#L114):

```dart
Future<Map<String, dynamic>> _$CustomerToRest(Customer instance,
    {RestProvider provider, OfflineFirstWithRestRepository repository}) async {
  return {
    'id': instance.id,
    'first_name': instance.firstName,
    'last_name': instance.lastName,
    'pizza_ids': instance.pizzas?.map((s) => s.id)?.toList()
  };
}
```

The adapters are the best place to look for what data is going to be transmitted to and from a provider.

**Comment by mrmeyers99** [comment]
Ok, I assumed that since the upsert was saving both the new pizza and the association in the client that it would also handle creating the pizza on the server, but my assumption was wrong.  Brick won't send any event for just the new association?  This seems a little confusing because my endpoint that saves the pizzas needs to allow a nullable foreign key to the customer until the customer upsert comes.  Then I have to check every pizza id I get in that request to make sure it's associated with that customer.  It would be nice to either get the customer id in the pizza request or have a better way to know which associations are new on the customer request.

**Comment by tshedor** [comment]
@mrmeyers99 Brick will send what's in the REST adapter. 

What you want sounds like nested payloads. If you don't include the `@OfflineFirstWhere` annotation, the generated `ToRest` adapter produces a payload that [would be the same](https://github.com/greenbits/brick/blob/master/packages/brick_offline_first/example/lib/app/adapters/kitchen_sink_adapter.g.dart#L78-L80) as if you were sending to the association's endpoint. 

This way, you'll have the pizza's foreign key in the customer payload.

**Comment by tshedor** [comment]
@mrmeyers99 I'm going to close this issue for now; if this didn't work out for you please feel free to reopen.
