### ISSUE TITLE
When are Requets Removed With "Offline First With Rest" Repository?

### ISSUE THREAD

**Issue by SubutaDan** [greenbits/brick#135]
Hello,
I have had trouble understanding this section of the doc:

_Offline First With Rest Repository 
OfflineFirstWithRestRepository streamlines the REST integration with an OfflineFirstRepository. A serial queue is included to track REST requests in a separate SQLite database, only removing requests when a response is not returned from the host (i.e. the device has lost internet connectivity)._

I would have thought that requests would be removed when a response (perhaps only some kinds of responses; maybe not a 500) is returned from the host.  Do I have this backwards?
Thanks.
-Dan

**Comment by tshedor** [comment]
@SubutaDan you're right, that's a typo. Nice catch.

**Comment by SubutaDan** [comment]
@tshedor , I have been puzzling over a related topic.  Under some error conditions I would like the request to be retained and retried later.  Under other error conditions I would want the request to be removed from the queue.  I guess whether the response is retained and later retried or removed from the queue depends on the http response.  Is that correct?

How do I tell Brick under what circumstances (for which http responses) to remove a request from the queue and under what circumstances to leave the request on the queue and try again later?

BTW, would you have preferred a new issue in this case or is it ok from your perspective that I extended the discussion the way I have?

Thanks.

-Dan

**Comment by tshedor** [comment]
@SubutaDan I added the trailing sentence to the documentation in the tagged commit above:

> `OfflineFirstWithRestRepository` streamlines the REST integration with an `OfflineFirstRepository`. A serial queue is included to track REST requests in a separate SQLite database, only removing requests when a response is returned from the host (i.e. the device has lost internet connectivity). See `OfflineFirstWithRest#reattemptForStatusCodes`.

In short, you can modify the retry status codes by changing the value of `reattemptForStatusCodes`. 

Re: new issue, I'd always prefer a new issue after the original query has been resolved. It helps keep the threads narrow (in case they need to be reviewed in the future), and the problems scoped. 

That said, I'm going to close this issue because I believe the text added in  de36337 includes the reference to the right property to change, and I'm going to merge that today. If you find that one an insufficient explanation, please feel free to open a fresh issue and we can review solutions there.
