### ISSUE TITLE
Improve My Understanding of Domains

### ISSUE THREAD

**Issue by SubutaDan** [greenbits/brick#140]
Hi @tshedor ,

I am still fuzzy about the definition of "domain".  The glossary says they are the encompassing system.  I think that Rest, Sqlite, Offline First, and Offline First with Rest are all  domains. Is that correct?  Does off-the-shelf Brick provide any other domains?

How is a domain manifested in the application code?   Is it something like "Each model that Brick will manage must have an annotation indicating the domain to which it belongs, and each repository must have an annotation indicating the domain for which it provides processing"?  

Does Brick look for cases where the annotations match, for example:  @ConnectOfflineFirstWithRest on the model matches OfflineFirstWithRestRepository on the repository?  And when it finds a match does Brick  generate the appropriate code for the model given its domain, and associate that code with the corresponding repository?

Thanks very much.

-Dan

**Comment by tshedor** [comment]
@SubutaDan 

>  think that Rest, Sqlite, Offline First, and Offline First with Rest are all domains. Is that correct?

That is correct. Or, that those are _each_ a domain.

> Does off-the-shelf Brick provide any other domains?

It does not

> How is a domain manifested in the application code?

In app code, domains are repositories or models. The bulk of the domain is in the generators, which the application code rarely if ever is concerned with. I say rarely because you may customize a generator with `fromGenerator` or `toGenerator`. 

Further, you should be primarily concerned with a single domain in app code (i.e. OfflineFirstWithRest) and only reference others that it builds from as necessary. 

>  Is it something like "Each model that Brick will manage must have an annotation indicating the domain to which it belongs, and each repository must have an annotation indicating the domain for which it provides processing"?

The documentation on domains is intentionally light because it's almost exclusively an internal definition. "Domains" is a shortcut word instead of saying "the generator, the annotation, the provider, the adapter, the model". 

As to the specifics of your statement, each model does not necessarily need an annotation. Annotations are used to trigger static code analysis in the generator. So if a provider or repository does not require code generation, it wouldn't require an annotation. 

In a lot of ways, I'd like to move past annotations because I believe they're extra code and I **hate** stringifying methods like `restEndpoint` or `fromGenerator`, but they're The Dart Way for defining configuration ahead of analysis. 

> Does Brick look for cases where the annotations match, for example: @ConnectOfflineFirstWithRest on the model matches OfflineFirstWithRestRepository on the repository?

IIRC, `@ConnectOfflineFirstWithRest` is only defined for the configuration properties. The checking to determine exactly how to serialize a model (i.e. if it's a sibling model where you have two OFWRModels, the adapter will generate code that makes a SQLite association) is done with the class type itself.

> And when it finds a match does Brick generate the appropriate code for the model given its domain, and associate that code with the corresponding repository?

Yes, with the caveat that generators are not repository-dependent (unless you're using a repository build package like BOFWRGenerators). But even in those cases, the repository build packages should largely be a subset of provider packages. That way, adapters are generated to be **provider-specific** not repository specific. This allows future development to incorporate multiple domains into a new domain (e.g. a Rest+Sqlite+Firebase+GraphQL repository).

**Comment by tshedor** [comment]
@SubutaDan I'm going to close this due to inactivity; I'd really appreciate a PR with documentation around your discoveries
