### ISSUE TITLE
Issue running flutter pub run build_runner run

### ISSUE THREAD

**Issue by mrmeyers99** [greenbits/brick#152]
I'm getting an issue when trying to run `flutter pub run build_runner run` to generate my migrations/adapaters.  I've tried it both with the latest version of and with an older version.  I'm doing this using a Github Action.  Here's my workflow file:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.6'
    - run: flutter pub get
    - run: flutter pub run build_runner run
```

Here's my dev depdendencies from my `pubspec.yml` file.

```dev_dependencies:
  sqflite_common: ^1.0.2+1
  sqflite_common_ffi: ^1.1.1

  flutter_test:
    sdk: flutter
  brick_offline_first_with_rest_build:
    git:
      url: https://github.com/greenbits/brick.git
      path: packages/brick_offline_first_with_rest_build
  build_runner: any
```

Here's the error that I'm getting when running this.

```
Run flutter pub run build_runner run
[INFO] Generating build script...
[INFO] Generating build script completed, took 443ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 16.6s

[SEVERE] Must specify an executable to run.
[SEVERE] Performs a single build, and executes a Dart script with the given arguments.

Usage: build_runner run [build-arguments] <executable> [-- [script-arguments]]
```

I've also tried specifying a few recent commit refs instead of using the latest and they have a different error.  For example, when I depend on commit `98601ddabf75adbbc368eeb2b570eb5b8b373e01` like this:
```
  brick_offline_first_with_rest_build:
    git:
      url: https://github.com/greenbits/brick.git
      ref: 98601ddabf75adbbc368eeb2b570eb5b8b373e01
      path: packages/brick_offline_first_with_rest_build
```

Then I get a mismatch between the types it's trying to use when creating a `SchemaColumn` in `offline_first_sqlite_builders.dart`.  It's trying to send a `Type` instead of a `Column`.
```
Run flutter pub run build_runner run
[INFO] Generating build script...
[INFO] Generating build script completed, took 427ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 9.2s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] /opt/hostedtoolcache/flutter/1.22.4-stable/x64/.pub-cache/git/brick-98601ddabf75adbbc368eeb2b570eb5b8b373e01/packages/brick_offline_first_with_rest_build/lib/src/offline_first_sqlite_builders.dart:29:23: Error: The argument type 'Type' can't be assigned to the parameter type 'Column'. - 'Type' is from 'dart:core'. - 'Column' is from 'package:brick_sqlite_abstract/src/db/migration.dart' ('/opt/hostedtoolcache/flutter/1.22.4-stable/x64/.pub-cache/hosted/pub.dartlang.org/brick_sqlite_abstract-0.1.0/lib/src/db/migration.dart').        sqliteChecker.asPrimitive,                      ^
pub finished with exit code 78
Error: Process completed with exit code 78.
```

Any help here would be appreciated!

I created a new project to make sure it wasn't anything weird that I had done in my project.  You can see that project here: https://github.com/mrmeyers99/test-brick/

Here are the logs from the output when I used the latest `brick_offline_first_with_rest_build`.
https://github.com/mrmeyers99/test-brick/runs/2139242677?check_suite_focus=true

Here are the logs from when I specified commit `98601ddabf75adbbc368eeb2b570eb5b8b373e01`
https://github.com/mrmeyers99/test-brick/runs/2139274326?check_suite_focus=true

**Comment by tshedor** [comment]
@mrmeyers99 Sorry about all this confusion. The null safety migration has a long tail. The core team recently published a null safe `build` and `source_gen` package (recent being last week), which is used by Brick to generate adapters, and I'm trying to play catchup. I've got a good start, but these upgrades aren't just null safety, they're also deprecations, so this knot is hard to untie.

I have a few recommendations to try:

1. The specific error that's being thrown is due to a change in how migrations are generated within Brick per #44 . At the time I believed this was a smooth upgrade because it would only affect `schema.g.dart`, but now I worry that the problem is severe for version-controlled, prior migrations. So two options for you here: version lock `brick_sqlite_abstract: 0.0.9+1` (you may need to do this in `dependency_overrides`). Or carefully edit your historical migrations to specify the second unnamed argument as an enum (such as replacing `, String,` with `, Column.varchar,`).
1. Use brick_offline_first_with_rest_build from pub.dev: `brick_offline_first_with_rest_build: any`. I recently published this as a package and the stable version will be locked out of null safety.
2. I see you've specified your flutter version in the GH actions (`flutter-version: '1.22.6'`) but your log output shows a different version: `1.22.4-stable`. I'm very green to GH actions, but I'm immediately worried that your build runner is operating in a lane (? workflow?) that has not completed `flutter pub get` and so it doesn't have the dependencies that were checked out as part of your setup with `flutter-version: '1.22.6'`. Do GH actions allow artifacts to persist between workflows? Perhaps `~/.pub-cache` isn't available? Could you please see why these two Flutter versions differ?
3. If you can stomach the wait, I think I can migrate the rest of the packages to null safety this week which should unify `master`.

**Comment by tshedor** [comment]
@mrmeyers99 I'm going to close this due to inactivity, please reopen if the above doesn't work.
