### ISSUE TITLE
Wrong working of migration

### ISSUE THREAD

**Issue by polRk** [greenbits/brick#159]
If I have a column with the DateTime type (in the DB it is a string), how can I convert the type to the String type?

```
DropColumn('closed_at', onTable: 'TaskDto'),
InsertColumn('closed_at', Column.varchar, onTable: 'TaskDto'),
``` 

I want to store only date in closed_at:

BEFORE: 2020-01-01T00:00
AFTER: 2020-01-01

**Comment by tshedor** [comment]
@polRk Those dates are functionally the same, aren't they? What happens when you store a time with minutes? 

The dart generators invoke `toIso8601String()` and on the other side invoke `DateTime.tryParse()`. I'd recommend testing your DateTime objects in [Dart Pad](https://dartpad.dev/?null_safety=true) to see how Dart natively converts the times.

**Comment by polRk** [comment]
The problem is that brick stores the dateTime in UTC, and I need to store it in local time. 

How can I remove the toIso8601String() behavior?

**Comment by polRk** [comment]
I am interested in the question of how to make the migration without deleting the data.
Now: `insertColumn+deleteColumn`
I want to something like this: ```
  insertColumn (temp_orders)
  moveData(orders, temp_orders)
  deleteColumn(orders)
  insertColumn(orders)
  moveData(temp_orders, orders)
```

**Comment by tshedor** [comment]
@polRk you could use a custom generator, such as `@Sqlite(fromGenerator: '%DATA_PROPERTY%.toString()', toGenerator: '%INSTANCE_PROPERTY%?.toString()')`. That will override the default generator.

**Comment by tshedor** [comment]
@polRk I'm going to close this due to inactivity, let me know if the above didn't work for you.
