### ISSUE TITLE
Crash with nullable enumAsString field

### ISSUE THREAD

**Issue by pkozlovskiy** [greenbits/brick#180]
In model i have field
```
@Rest(enumAsString: true)
final TaskStatus? status;
```

But in adapter 
`status: RestAdapter.enumValueFromName(TaskStatus.values, data['status']),`
if I get data['status']=null enumValueFromName is crashed becase it want String only
`  static T? enumValueFromName<T>(Iterable<T> enumValues, String enumName) {`

**Comment by tshedor** [comment]
Hey @pkozlovskiy there are two guesses I have for you:

1. You need to regenerate your adapter. 
2. Try setting `@Rest(nullable: true)` on this member. [Looking at the source code](https://github.com/greenbits/brick/blob/master/packages/brick_build/lib/src/serdes_generator.dart#L214-L215), the rest adapter should return `null` instead of trying to pass `data['status']` to that `enumValueFromName`.
