### ISSUE TITLE
Suport with OfflineFirstSerdes

### ISSUE THREAD

**Issue by porfirioribeiro** [greenbits/brick#47]
Some serdes might already extend a different class, in my understanding `OfflineFirstSerdes` could be used as a mixin, but the builder will not detect it.

```dart
class MySerde extends SomeBaseClass with OfflineFirstSerdes<String, String>
```

I guess it's a matter of changing how the builder detects this?

**Comment by tshedor** [comment]
@porfirioribeiro `OfflineFirstSerdes` has to be used as its own class for the analyzer to detect it. This isn't available as a mixin because classes extending `OfflineFirstSerdes` need to have provider-specific factories like `toRest`, and mixins shouldn't anticipate or declare constructors. You can approach this from two directions:

```dart
abstract class BaseModelClass<R, S> extends OfflineFirstSerdes<R, S> {}

class MyModel<String, String> extends BaseModelClass {}
```

or, if you need the concerns very separated:

```dart
abstract class BaseModelClass {}
abstract class SerdesBaseModelClass<R, S> extends OfflineFirstSerdes<R, S> {}

class MySerdesModel<String, String> extends SerdesBaseModelClass {}
class MyModel extends BaseModelClass {}
```

That all said, I think a better pattern would be to `extend OfflineFirstSerdes with YourMixin` instead of the inverse.

**Comment by porfirioribeiro** [comment]
Thanks for the explanation, it makes sense!
